[package]
name = "pattern_03_di_container"
version = "0.1.0"
authors = ["mori5321 <moriwm77@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
waiter_di = { version = "1.6.5", features = ["async"] }

